// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBET7S4OMOLMdU6N_cKIJ9k73wqR25ZV28',
    appId: '1:345011764331:web:520b3b3f53415f2e34052e',
    messagingSenderId: '345011764331',
    projectId: 'flutter-project-42900',
    authDomain: 'flutter-project-42900.firebaseapp.com',
    storageBucket: 'flutter-project-42900.firebasestorage.app',
    measurementId: 'G-YB33378H9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXqJCCjaOmc7jhtH6saG4Lpa57d6O9-M',
    appId: '1:345011764331:android:403aff09befe8fff34052e',
    messagingSenderId: '345011764331',
    projectId: 'flutter-project-42900',
    storageBucket: 'flutter-project-42900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8oNy-YFoQR-uN4j2v5eQiCREAiyOB9bc',
    appId: '1:345011764331:ios:9162c9a9ee8cd88e34052e',
    messagingSenderId: '345011764331',
    projectId: 'flutter-project-42900',
    storageBucket: 'flutter-project-42900.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8oNy-YFoQR-uN4j2v5eQiCREAiyOB9bc',
    appId: '1:345011764331:ios:9162c9a9ee8cd88e34052e',
    messagingSenderId: '345011764331',
    projectId: 'flutter-project-42900',
    storageBucket: 'flutter-project-42900.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBET7S4OMOLMdU6N_cKIJ9k73wqR25ZV28',
    appId: '1:345011764331:web:9104fb97ebbf0fbb34052e',
    messagingSenderId: '345011764331',
    projectId: 'flutter-project-42900',
    authDomain: 'flutter-project-42900.firebaseapp.com',
    storageBucket: 'flutter-project-42900.firebasestorage.app',
    measurementId: 'G-EE1YBNL51D',
  );
}
